### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by kghost** [greven/oUF_lumen#20]
I used to work on the develop branch, and trying to improve this addon, but it turns out that my branch is diverging very quickly.

You can check my changes [here](https://github.com/kghost-personal/oUF_Lumen).

There are a few major changes I committed:

1. Added partytarget and partypet frame
2. Added raid frame
3. Added `aurawatchers` element, which is used to monitor hots applied by the player, very useful for resto druid
4. Added a configuration panel using Ace3

And lots of minor changes:

1. CustomClick element, cast spells with single click to the party or raid frame
2. Raise RaidIndicator and RaidRole icons above health bar frame
3. Create a out of combat frame, and move several non-essential element in to this frame, like character level and class
4. Use `Masque` to theme all icons
5. Add phase indicator, showing why is party member in the different phase

I'm using [LuaFormatter](https://github.com/Koihik/LuaFormatter) to format the lua code

I want to push all of them, but it will be a very tedious work to push them one by one. If you prefer these changes, we can work together, and figure out how to cooperate.

**Comment by greven** [comment]
Hi mate!

Those are some really great changes. 👍 
Thing is I'm actually currently in the process or [re-writing everything into a combined UI package](https://github.com/greven/LumenUI) (Frames, actionbars, etc).

So I will kind of be discontinuing updating oUF_Lumen and focus on this new UI. 

I will for sure use some elements that you added, like Masque support, (haven't really thought about adding that ever).
oUF_Lumen was ok in terms of code but had some glaring flaws, like no Raid Frames (it had years ago, but had to drop it for lack of time to maintain it with the upcoming API changes).

So, I'll tell you what, like you say, it would be quite the effort to integrate everything into the upstream.
I guess it would be better if you maintain your fork, and if you want you can even rename your fork into its own thing and publish it (if you wish so).

I can, and will probably had a last pass on the code before I "drop it", any PRs will be welcome anyway but it will be hard for me to maintain it since I won't be using it actively. But I will look at your changes and most probably incorporate the most obvious ones into oUF_Lumen.

Is that fair enough?
