### ISSUE TITLE
about debuffs

### ISSUE THREAD

**Issue by CrisReus** [greven/oUF_Lumen#9]
If you accept change requests, I would love to see an option for target debuffs.
Show others debuffs on the target frame.
On the upper left or right.
Thanks for your work, I love the layouts.

**Comment by greven** [comment]
You can see debuffs. That is what the BarTimers are for. But instead of seeing everything you just see the ones you set up on the filters file.
There isn't other way to add it since the Target Element already has the debuffs set up this way.

You can always enable the nameplates and see all debuffs there too. Of course, you only see your own debuffs.
